version: 2

node: &node
  docker:
    - image: circleci/node:9.11.1

jobs:
  create_base_env:
    <<: *node
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
            - dependencies
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: .
          paths:
            - "*"
  
  test:
    <<: *node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint the code
          command: yarn lint
      - run:
          name: Unit test
          command: yarn unit --ci --testResultsProcessor="jest-junit"
      - run:
          name: End to end test
          command: yarn e2e
      - run:
          name: Export code coverage to Codecov
          command: yarn ccov
      - store_test_results:
          path: ./test/unit/coverage

  build:
    <<: *node
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build the app
          command: yarn build
      - store_artifacts:
          path: ./dist
      - persist_to_workspace:
          root: .
          paths:
            - "./dist"

  dockerize:
    machine: true
    environment:
      IMAGE: "socialementcompetents/hackafront"
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Connect to Docker Hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build the container
          command: docker build -t $IMAGE:$CIRCLE_SHA1 -f CI.Dockerfile .
      - run:
          name: Add latest tag
          command: docker tag $IMAGE:$CIRCLE_SHA1 $IMAGE:latest
      - run:
          name: Push to the Docker Hub registry
          command: docker push $IMAGE:$CIRCLE_SHA1 && docker push $IMAGE:latest

  publish:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Zip and publish the built files to Github Releases
          command: |
            sudo apt-get update &&
            sudo apt-get install -y zip bzip2 tar &&
            cd dist &&
            chmod +x ../release.sh &&
            ../release.sh

workflows:
  version: 2
  test_build_deploy:
    jobs:
      - create_base_env:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - create_base_env
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - create_base_env
          filters:
            tags:
              only: /.*/
      - dockerize:
          requires:
            - build
            - test
          filters:
            branches:
              only: master
      - publish:
          requires:
            - build
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
